// This file is generated by bindgen
// Do not modify this file manually!

declare module 'chromatic' {

export class chrome {
}
namespace chrome {
export class blink {
	/**
     * 
     * @param arg0: ((arg1: string) => string)
     * @returns void
     */
    static add_blink_parse_html_manipulator(arg0: ((arg1: string) => string)): void
	static is_parse_html_manipulator_available(): boolean
}
}
namespace chrome.blink {
export class blink_parse_manipulate_context {
	html: string
	url: string
}
}
export class infra {
	/**
     * 
     * @param msg: qjs.rest<string>
     * @returns void
     */
    static log(msg: qjs.rest<string>): void
}
}

