// This file is generated by Breeze.JS Bindgen (https://github.com/breeze-shell/breeze-js-bindgen)
// Do not modify this file manually!

#pragma once
#include "binding_types.h"
#include "quickjspp.hpp"

template <typename T>
struct js_bind {
    static void bind(qjs::Context::Module &mod) {}
};

template <> struct qjs::js_traits<chromatic::js::chrome> {
    static chromatic::js::chrome unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::chrome obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::chrome &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::chrome> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::chrome>("chrome")
            .constructor<>()
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::chrome::blink> {
    static chromatic::js::chrome::blink unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::chrome::blink obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::chrome::blink &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::chrome::blink> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::chrome::blink>("chrome::blink")
            .constructor<>()
                .static_fun<&chromatic::js::chrome::blink::add_blink_parse_html_manipulator>("add_blink_parse_html_manipulator")
                .static_fun<&chromatic::js::chrome::blink::is_parse_html_manipulator_available>("is_parse_html_manipulator_available")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::chrome::blink::blink_parse_manipulate_context> {
    static chromatic::js::chrome::blink::blink_parse_manipulate_context unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::chrome::blink::blink_parse_manipulate_context obj;

        obj.html = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "html"));

        obj.url = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "url"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::chrome::blink::blink_parse_manipulate_context &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "html", js_traits<std::string>::wrap(ctx, val.html));

        JS_SetPropertyStr(ctx, obj, "url", js_traits<std::string>::wrap(ctx, val.url));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::chrome::blink::blink_parse_manipulate_context> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::chrome::blink::blink_parse_manipulate_context>("chrome::blink::blink_parse_manipulate_context")
            .constructor<>()
                .fun<&chromatic::js::chrome::blink::blink_parse_manipulate_context::html>("html")
                .fun<&chromatic::js::chrome::blink::blink_parse_manipulate_context::url>("url")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::infra> {
    static chromatic::js::infra unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::infra obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::infra &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::infra> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::infra>("infra")
            .constructor<>()
                .static_fun<&chromatic::js::infra::log>("log")
            ;
    }
};

inline void bindAll(qjs::Context::Module &mod) {

    js_bind<chromatic::js::chrome>::bind(mod);

    js_bind<chromatic::js::chrome::blink>::bind(mod);

    js_bind<chromatic::js::chrome::blink::blink_parse_manipulate_context>::bind(mod);

    js_bind<chromatic::js::infra>::bind(mod);

}
