// This file is generated by Breeze.JS Bindgen (https://github.com/breeze-shell/breeze-js-bindgen)
// Do not modify this file manually!

#pragma once
#include "binding_types.h"
#include "quickjspp.hpp"

template <typename T>
struct js_bind {
    static void bind(qjs::Context::Module &mod) {}
};

template <> struct qjs::js_traits<chromatic::js::NativePointer> {
    static chromatic::js::NativePointer unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativePointer obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativePointer &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativePointer> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativePointer>("NativePointer")
            .constructor<uint64_t>()
                .fun<&chromatic::js::NativePointer::value>("value")
                .fun<&chromatic::js::NativePointer::toString>("toString")
                .fun<&chromatic::js::NativePointer::toInt32>("toInt32")
                .fun<&chromatic::js::NativePointer::toUInt32>("toUInt32")
                .fun<&chromatic::js::NativePointer::toNumber>("toNumber")
                .fun<&chromatic::js::NativePointer::isNull>("isNull")
                .fun<&chromatic::js::NativePointer::equals>("equals")
                .fun<&chromatic::js::NativePointer::compare>("compare")
                .fun<&chromatic::js::NativePointer::add>("add")
                .fun<&chromatic::js::NativePointer::sub>("sub")
                .fun<&chromatic::js::NativePointer::bitwiseAnd>("bitwiseAnd")
                .fun<&chromatic::js::NativePointer::bitwiseOr>("bitwiseOr")
                .fun<&chromatic::js::NativePointer::bitwiseXor>("bitwiseXor")
                .fun<&chromatic::js::NativePointer::shr>("shr")
                .fun<&chromatic::js::NativePointer::shl>("shl")
                .fun<&chromatic::js::NativePointer::bitwiseNot>("bitwiseNot")
                .fun<&chromatic::js::NativePointer::readU8>("readU8")
                .fun<&chromatic::js::NativePointer::readS8>("readS8")
                .fun<&chromatic::js::NativePointer::readU16>("readU16")
                .fun<&chromatic::js::NativePointer::readS16>("readS16")
                .fun<&chromatic::js::NativePointer::readU32>("readU32")
                .fun<&chromatic::js::NativePointer::readS32>("readS32")
                .fun<&chromatic::js::NativePointer::readU64>("readU64")
                .fun<&chromatic::js::NativePointer::readS64>("readS64")
                .fun<&chromatic::js::NativePointer::readFloat>("readFloat")
                .fun<&chromatic::js::NativePointer::readDouble>("readDouble")
                .fun<&chromatic::js::NativePointer::readPointer>("readPointer")
                .fun<&chromatic::js::NativePointer::readByteArray>("readByteArray")
                .fun<&chromatic::js::NativePointer::readCString>("readCString")
                .fun<&chromatic::js::NativePointer::readUtf8String>("readUtf8String")
                .fun<&chromatic::js::NativePointer::writeU8>("writeU8")
                .fun<&chromatic::js::NativePointer::writeS8>("writeS8")
                .fun<&chromatic::js::NativePointer::writeU16>("writeU16")
                .fun<&chromatic::js::NativePointer::writeS16>("writeS16")
                .fun<&chromatic::js::NativePointer::writeU32>("writeU32")
                .fun<&chromatic::js::NativePointer::writeS32>("writeS32")
                .fun<&chromatic::js::NativePointer::writeU64>("writeU64")
                .fun<&chromatic::js::NativePointer::writeS64>("writeS64")
                .fun<&chromatic::js::NativePointer::writeFloat>("writeFloat")
                .fun<&chromatic::js::NativePointer::writeDouble>("writeDouble")
                .fun<&chromatic::js::NativePointer::writePointer>("writePointer")
                .fun<&chromatic::js::NativePointer::writeByteArray>("writeByteArray")
                .fun<&chromatic::js::NativePointer::writeUtf8String>("writeUtf8String")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::console> {
    static chromatic::js::console unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::console obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::console &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::console> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::console>("console")
            .constructor<>()
                .static_fun<&chromatic::js::console::log>("log")
                .static_fun<&chromatic::js::console::error>("error")
                .static_fun<&chromatic::js::console::warn>("warn")
                .static_fun<&chromatic::js::console::info>("info")
                .static_fun<&chromatic::js::console::debug>("debug")
                .static_fun<&chromatic::js::console::trace>("trace")
                .static_fun<&chromatic::js::console::group>("group")
                .static_fun<&chromatic::js::console::groupEnd>("groupEnd")
                .static_fun<&chromatic::js::console::table>("table")
                .static_fun<&chromatic::js::console::time>("time")
                .static_fun<&chromatic::js::console::timeEnd>("timeEnd")
                .static_fun<&chromatic::js::console::count>("count")
                .static_fun<&chromatic::js::console::countReset>("countReset")
                .static_fun<&chromatic::js::console::dir>("dir")
                .static_fun<&chromatic::js::console::dirxml>("dirxml")
                .static_fun<&chromatic::js::console::profile>("profile")
                .static_fun<&chromatic::js::console::profileEnd>("profileEnd")
                .static_fun<&chromatic::js::console::timeStamp>("timeStamp")
                .static_fun<&chromatic::js::console::timeline>("timeline")
                .static_fun<&chromatic::js::console::timelineEnd>("timelineEnd")
                .static_fun<&chromatic::js::console::timeLog>("timeLog")
                .static_fun<&chromatic::js::console::timeLine>("timeLine")
                .static_fun<&chromatic::js::console::timeLineEnd>("timeLineEnd")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::NativeSoftwareBreakpoint> {
    static chromatic::js::NativeSoftwareBreakpoint unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativeSoftwareBreakpoint obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativeSoftwareBreakpoint &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativeSoftwareBreakpoint> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativeSoftwareBreakpoint>("NativeSoftwareBreakpoint")
            .constructor<>()
                .static_fun<&chromatic::js::NativeSoftwareBreakpoint::set>("set")
                .static_fun<&chromatic::js::NativeSoftwareBreakpoint::remove>("remove")
                .static_fun<&chromatic::js::NativeSoftwareBreakpoint::removeAll>("removeAll")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::InstructionInfo> {
    static chromatic::js::InstructionInfo unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::InstructionInfo obj;

        obj.mnemonic = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "mnemonic"));

        obj.opStr = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "opStr"));

        obj.size = js_traits<int>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "size"));

        obj.bytes = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "bytes"));

        obj.address = js_traits<std::shared_ptr<chromatic::js::NativePointer>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "address"));

        obj.groups = js_traits<std::vector<int>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "groups"));

        obj.regsRead = js_traits<std::vector<int>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "regsRead"));

        obj.regsWrite = js_traits<std::vector<int>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "regsWrite"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::InstructionInfo &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "mnemonic", js_traits<std::string>::wrap(ctx, val.mnemonic));

        JS_SetPropertyStr(ctx, obj, "opStr", js_traits<std::string>::wrap(ctx, val.opStr));

        JS_SetPropertyStr(ctx, obj, "size", js_traits<int>::wrap(ctx, val.size));

        JS_SetPropertyStr(ctx, obj, "bytes", js_traits<std::string>::wrap(ctx, val.bytes));

        JS_SetPropertyStr(ctx, obj, "address", js_traits<std::shared_ptr<chromatic::js::NativePointer>>::wrap(ctx, val.address));

        JS_SetPropertyStr(ctx, obj, "groups", js_traits<std::vector<int>>::wrap(ctx, val.groups));

        JS_SetPropertyStr(ctx, obj, "regsRead", js_traits<std::vector<int>>::wrap(ctx, val.regsRead));

        JS_SetPropertyStr(ctx, obj, "regsWrite", js_traits<std::vector<int>>::wrap(ctx, val.regsWrite));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::InstructionInfo> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::InstructionInfo>("InstructionInfo")
            .constructor<chromatic::js::InstructionInfo>()
                .fun<&chromatic::js::InstructionInfo::mnemonic>("mnemonic")
                .fun<&chromatic::js::InstructionInfo::opStr>("opStr")
                .fun<&chromatic::js::InstructionInfo::size>("size")
                .fun<&chromatic::js::InstructionInfo::bytes>("bytes")
                .fun<&chromatic::js::InstructionInfo::address>("address")
                .fun<&chromatic::js::InstructionInfo::groups>("groups")
                .fun<&chromatic::js::InstructionInfo::regsRead>("regsRead")
                .fun<&chromatic::js::InstructionInfo::regsWrite>("regsWrite")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::InstructionAnalysis> {
    static chromatic::js::InstructionAnalysis unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::InstructionAnalysis obj;

        obj.isBranch = js_traits<bool>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "isBranch"));

        obj.isCall = js_traits<bool>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "isCall"));

        obj.isRelative = js_traits<bool>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "isRelative"));

        obj.target = js_traits<std::shared_ptr<chromatic::js::NativePointer>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "target"));

        obj.isPcRelative = js_traits<bool>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "isPcRelative"));

        obj.size = js_traits<int>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "size"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::InstructionAnalysis &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "isBranch", js_traits<bool>::wrap(ctx, val.isBranch));

        JS_SetPropertyStr(ctx, obj, "isCall", js_traits<bool>::wrap(ctx, val.isCall));

        JS_SetPropertyStr(ctx, obj, "isRelative", js_traits<bool>::wrap(ctx, val.isRelative));

        JS_SetPropertyStr(ctx, obj, "target", js_traits<std::shared_ptr<chromatic::js::NativePointer>>::wrap(ctx, val.target));

        JS_SetPropertyStr(ctx, obj, "isPcRelative", js_traits<bool>::wrap(ctx, val.isPcRelative));

        JS_SetPropertyStr(ctx, obj, "size", js_traits<int>::wrap(ctx, val.size));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::InstructionAnalysis> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::InstructionAnalysis>("InstructionAnalysis")
            .constructor<chromatic::js::InstructionAnalysis>()
                .fun<&chromatic::js::InstructionAnalysis::isBranch>("isBranch")
                .fun<&chromatic::js::InstructionAnalysis::isCall>("isCall")
                .fun<&chromatic::js::InstructionAnalysis::isRelative>("isRelative")
                .fun<&chromatic::js::InstructionAnalysis::target>("target")
                .fun<&chromatic::js::InstructionAnalysis::isPcRelative>("isPcRelative")
                .fun<&chromatic::js::InstructionAnalysis::size>("size")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::XrefResult> {
    static chromatic::js::XrefResult unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::XrefResult obj;

        obj.address = js_traits<std::shared_ptr<chromatic::js::NativePointer>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "address"));

        obj.type = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "type"));

        obj.size = js_traits<int>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "size"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::XrefResult &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "address", js_traits<std::shared_ptr<chromatic::js::NativePointer>>::wrap(ctx, val.address));

        JS_SetPropertyStr(ctx, obj, "type", js_traits<std::string>::wrap(ctx, val.type));

        JS_SetPropertyStr(ctx, obj, "size", js_traits<int>::wrap(ctx, val.size));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::XrefResult> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::XrefResult>("XrefResult")
            .constructor<chromatic::js::XrefResult>()
                .fun<&chromatic::js::XrefResult::address>("address")
                .fun<&chromatic::js::XrefResult::type>("type")
                .fun<&chromatic::js::XrefResult::size>("size")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::NativeDisassembler> {
    static chromatic::js::NativeDisassembler unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativeDisassembler obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativeDisassembler &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativeDisassembler> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativeDisassembler>("NativeDisassembler")
            .constructor<>()
                .static_fun<&chromatic::js::NativeDisassembler::disassembleOne>("disassembleOne")
                .static_fun<&chromatic::js::NativeDisassembler::disassemble>("disassemble")
                .static_fun<&chromatic::js::NativeDisassembler::analyzeInstruction>("analyzeInstruction")
                .static_fun<&chromatic::js::NativeDisassembler::findXrefs>("findXrefs")
                .static_fun<&chromatic::js::NativeDisassembler::findXrefsInModule>("findXrefsInModule")
                .static_fun<&chromatic::js::NativeDisassembler::findXrefsAsync>("findXrefsAsync")
                .static_fun<&chromatic::js::NativeDisassembler::findXrefsInModuleAsync>("findXrefsInModuleAsync")
                .static_fun<&chromatic::js::NativeDisassembler::filterInstructions>("filterInstructions")
                .static_fun<&chromatic::js::NativeDisassembler::filterInstructionsAsync>("filterInstructionsAsync")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::ExceptionType> {
    static chromatic::js::ExceptionType unwrap(JSContext *ctx, JSValueConst v) {
        return static_cast<chromatic::js::ExceptionType>(js_traits<int>::unwrap(ctx, v));
    }
    static JSValue wrap(JSContext *ctx, const chromatic::js::ExceptionType &val) noexcept {
        return js_traits<int>::wrap(ctx, static_cast<int>(val));
    }
};
template <> struct qjs::js_traits<chromatic::js::AccessType> {
    static chromatic::js::AccessType unwrap(JSContext *ctx, JSValueConst v) {
        return static_cast<chromatic::js::AccessType>(js_traits<int>::unwrap(ctx, v));
    }
    static JSValue wrap(JSContext *ctx, const chromatic::js::AccessType &val) noexcept {
        return js_traits<int>::wrap(ctx, static_cast<int>(val));
    }
};
template <> struct qjs::js_traits<chromatic::js::HandleAction> {
    static chromatic::js::HandleAction unwrap(JSContext *ctx, JSValueConst v) {
        return static_cast<chromatic::js::HandleAction>(js_traits<int>::unwrap(ctx, v));
    }
    static JSValue wrap(JSContext *ctx, const chromatic::js::HandleAction &val) noexcept {
        return js_traits<int>::wrap(ctx, static_cast<int>(val));
    }
};
template <> struct qjs::js_traits<chromatic::js::ExceptionContext> {
    static chromatic::js::ExceptionContext unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::ExceptionContext obj;

        obj.type = js_traits<chromatic::js::ExceptionType>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "type"));

        obj.faultAddress = js_traits<uint64_t>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "faultAddress"));

        obj.accessType = js_traits<chromatic::js::AccessType>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "accessType"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::ExceptionContext &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "type", js_traits<chromatic::js::ExceptionType>::wrap(ctx, val.type));

        JS_SetPropertyStr(ctx, obj, "faultAddress", js_traits<uint64_t>::wrap(ctx, val.faultAddress));

        JS_SetPropertyStr(ctx, obj, "accessType", js_traits<chromatic::js::AccessType>::wrap(ctx, val.accessType));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::ExceptionContext> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::ExceptionContext>("ExceptionContext")
            .constructor<>()
                    .property<&chromatic::js::ExceptionContext::getPc, &chromatic::js::ExceptionContext::setPc>("pc")
                .fun<&chromatic::js::ExceptionContext::getPc>("getPc")
                .fun<&chromatic::js::ExceptionContext::setPc>("setPc")
                .fun<&chromatic::js::ExceptionContext::setSingleStep>("setSingleStep")
                .fun<&chromatic::js::ExceptionContext::type>("type")
                .fun<&chromatic::js::ExceptionContext::faultAddress>("faultAddress")
                .fun<&chromatic::js::ExceptionContext::accessType>("accessType")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::NativeExceptionHandler> {
    static chromatic::js::NativeExceptionHandler unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativeExceptionHandler obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativeExceptionHandler &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativeExceptionHandler> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativeExceptionHandler>("NativeExceptionHandler")
            .constructor<>()
                .static_fun<&chromatic::js::NativeExceptionHandler::enable>("enable")
                .static_fun<&chromatic::js::NativeExceptionHandler::disable>("disable")
                .static_fun<&chromatic::js::NativeExceptionHandler::isEnabled>("isEnabled")
                .static_fun<&chromatic::js::NativeExceptionHandler::addCallback>("addCallback")
                .static_fun<&chromatic::js::NativeExceptionHandler::removeCallback>("removeCallback")
                .static_fun<&chromatic::js::NativeExceptionHandler::removeAllCallbacks>("removeAllCallbacks")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::NativeFFI> {
    static chromatic::js::NativeFFI unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativeFFI obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativeFFI &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativeFFI> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativeFFI>("NativeFFI")
            .constructor<>()
                .static_fun<&chromatic::js::NativeFFI::callFunction>("callFunction")
                .static_fun<&chromatic::js::NativeFFI::createCallback>("createCallback")
                .static_fun<&chromatic::js::NativeFFI::destroyCallback>("destroyCallback")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::NativeHardwareBreakpoint> {
    static chromatic::js::NativeHardwareBreakpoint unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativeHardwareBreakpoint obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativeHardwareBreakpoint &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativeHardwareBreakpoint> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativeHardwareBreakpoint>("NativeHardwareBreakpoint")
            .constructor<>()
                .static_fun<&chromatic::js::NativeHardwareBreakpoint::set>("set")
                .static_fun<&chromatic::js::NativeHardwareBreakpoint::remove>("remove")
                .static_fun<&chromatic::js::NativeHardwareBreakpoint::removeAll>("removeAll")
                .static_fun<&chromatic::js::NativeHardwareBreakpoint::maxBreakpoints>("maxBreakpoints")
                .static_fun<&chromatic::js::NativeHardwareBreakpoint::activeCount>("activeCount")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::NativeInterceptor> {
    static chromatic::js::NativeInterceptor unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativeInterceptor obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativeInterceptor &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativeInterceptor> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativeInterceptor>("NativeInterceptor")
            .constructor<>()
                .static_fun<&chromatic::js::NativeInterceptor::attach>("attach")
                .static_fun<&chromatic::js::NativeInterceptor::detach>("detach")
                .static_fun<&chromatic::js::NativeInterceptor::detachAll>("detachAll")
                .static_fun<&chromatic::js::NativeInterceptor::replace>("replace")
                .static_fun<&chromatic::js::NativeInterceptor::revert>("revert")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::ScanMatch> {
    static chromatic::js::ScanMatch unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::ScanMatch obj;

        obj.address = js_traits<std::shared_ptr<chromatic::js::NativePointer>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "address"));

        obj.size = js_traits<int>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "size"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::ScanMatch &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "address", js_traits<std::shared_ptr<chromatic::js::NativePointer>>::wrap(ctx, val.address));

        JS_SetPropertyStr(ctx, obj, "size", js_traits<int>::wrap(ctx, val.size));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::ScanMatch> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::ScanMatch>("ScanMatch")
            .constructor<chromatic::js::ScanMatch>()
                .fun<&chromatic::js::ScanMatch::address>("address")
                .fun<&chromatic::js::ScanMatch::size>("size")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::NativeMemory> {
    static chromatic::js::NativeMemory unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativeMemory obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativeMemory &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativeMemory> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativeMemory>("NativeMemory")
            .constructor<>()
                .static_fun<&chromatic::js::NativeMemory::readMemory>("readMemory")
                .static_fun<&chromatic::js::NativeMemory::safeReadMemory>("safeReadMemory")
                .static_fun<&chromatic::js::NativeMemory::writeMemory>("writeMemory")
                .static_fun<&chromatic::js::NativeMemory::allocateMemory>("allocateMemory")
                .static_fun<&chromatic::js::NativeMemory::freeMemory>("freeMemory")
                .static_fun<&chromatic::js::NativeMemory::protectMemory>("protectMemory")
                .static_fun<&chromatic::js::NativeMemory::patchCode>("patchCode")
                .static_fun<&chromatic::js::NativeMemory::flushIcache>("flushIcache")
                .static_fun<&chromatic::js::NativeMemory::copyMemory>("copyMemory")
                .static_fun<&chromatic::js::NativeMemory::scanMemory>("scanMemory")
                .static_fun<&chromatic::js::NativeMemory::scanModule>("scanModule")
                .static_fun<&chromatic::js::NativeMemory::scanMemoryAsync>("scanMemoryAsync")
                .static_fun<&chromatic::js::NativeMemory::scanModuleAsync>("scanModuleAsync")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::MemoryAccessDetails> {
    static chromatic::js::MemoryAccessDetails unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::MemoryAccessDetails obj;

        obj.address = js_traits<std::shared_ptr<chromatic::js::NativePointer>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "address"));

        obj.pageBase = js_traits<std::shared_ptr<chromatic::js::NativePointer>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "pageBase"));

        obj.operation = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "operation"));

        obj.rangeIndex = js_traits<int>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "rangeIndex"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::MemoryAccessDetails &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "address", js_traits<std::shared_ptr<chromatic::js::NativePointer>>::wrap(ctx, val.address));

        JS_SetPropertyStr(ctx, obj, "pageBase", js_traits<std::shared_ptr<chromatic::js::NativePointer>>::wrap(ctx, val.pageBase));

        JS_SetPropertyStr(ctx, obj, "operation", js_traits<std::string>::wrap(ctx, val.operation));

        JS_SetPropertyStr(ctx, obj, "rangeIndex", js_traits<int>::wrap(ctx, val.rangeIndex));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::MemoryAccessDetails> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::MemoryAccessDetails>("MemoryAccessDetails")
            .constructor<chromatic::js::MemoryAccessDetails>()
                .fun<&chromatic::js::MemoryAccessDetails::address>("address")
                .fun<&chromatic::js::MemoryAccessDetails::pageBase>("pageBase")
                .fun<&chromatic::js::MemoryAccessDetails::operation>("operation")
                .fun<&chromatic::js::MemoryAccessDetails::rangeIndex>("rangeIndex")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::NativeMemoryAccessMonitor> {
    static chromatic::js::NativeMemoryAccessMonitor unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativeMemoryAccessMonitor obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativeMemoryAccessMonitor &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativeMemoryAccessMonitor> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativeMemoryAccessMonitor>("NativeMemoryAccessMonitor")
            .constructor<>()
                .static_fun<&chromatic::js::NativeMemoryAccessMonitor::enable>("enable")
                .static_fun<&chromatic::js::NativeMemoryAccessMonitor::disable>("disable")
                .static_fun<&chromatic::js::NativeMemoryAccessMonitor::disableAll>("disableAll")
                .static_fun<&chromatic::js::NativeMemoryAccessMonitor::drainPending>("drainPending")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::SegmentInfo> {
    static chromatic::js::SegmentInfo unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::SegmentInfo obj;

        obj.base = js_traits<uint64_t>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "base"));

        obj.size = js_traits<uint64_t>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "size"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::SegmentInfo &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "base", js_traits<uint64_t>::wrap(ctx, val.base));

        JS_SetPropertyStr(ctx, obj, "size", js_traits<uint64_t>::wrap(ctx, val.size));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::SegmentInfo> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::SegmentInfo>("SegmentInfo")
            .constructor<>()
                .fun<&chromatic::js::SegmentInfo::base>("base")
                .fun<&chromatic::js::SegmentInfo::size>("size")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::ModuleInfo> {
    static chromatic::js::ModuleInfo unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::ModuleInfo obj;

        obj.name = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "name"));

        obj.base = js_traits<std::shared_ptr<chromatic::js::NativePointer>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "base"));

        obj.size = js_traits<int>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "size"));

        obj.path = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "path"));

        obj.segments = js_traits<std::vector<chromatic::js::SegmentInfo>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "segments"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::ModuleInfo &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "name", js_traits<std::string>::wrap(ctx, val.name));

        JS_SetPropertyStr(ctx, obj, "base", js_traits<std::shared_ptr<chromatic::js::NativePointer>>::wrap(ctx, val.base));

        JS_SetPropertyStr(ctx, obj, "size", js_traits<int>::wrap(ctx, val.size));

        JS_SetPropertyStr(ctx, obj, "path", js_traits<std::string>::wrap(ctx, val.path));

        JS_SetPropertyStr(ctx, obj, "segments", js_traits<std::vector<chromatic::js::SegmentInfo>>::wrap(ctx, val.segments));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::ModuleInfo> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::ModuleInfo>("ModuleInfo")
            .constructor<chromatic::js::ModuleInfo>()
                .fun<&chromatic::js::ModuleInfo::name>("name")
                .fun<&chromatic::js::ModuleInfo::base>("base")
                .fun<&chromatic::js::ModuleInfo::size>("size")
                .fun<&chromatic::js::ModuleInfo::path>("path")
                .fun<&chromatic::js::ModuleInfo::segments>("segments")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::RangeInfo> {
    static chromatic::js::RangeInfo unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::RangeInfo obj;

        obj.base = js_traits<std::shared_ptr<chromatic::js::NativePointer>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "base"));

        obj.size = js_traits<int>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "size"));

        obj.protection = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "protection"));

        obj.filePath = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "filePath"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::RangeInfo &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "base", js_traits<std::shared_ptr<chromatic::js::NativePointer>>::wrap(ctx, val.base));

        JS_SetPropertyStr(ctx, obj, "size", js_traits<int>::wrap(ctx, val.size));

        JS_SetPropertyStr(ctx, obj, "protection", js_traits<std::string>::wrap(ctx, val.protection));

        JS_SetPropertyStr(ctx, obj, "filePath", js_traits<std::string>::wrap(ctx, val.filePath));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::RangeInfo> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::RangeInfo>("RangeInfo")
            .constructor<chromatic::js::RangeInfo>()
                .fun<&chromatic::js::RangeInfo::base>("base")
                .fun<&chromatic::js::RangeInfo::size>("size")
                .fun<&chromatic::js::RangeInfo::protection>("protection")
                .fun<&chromatic::js::RangeInfo::filePath>("filePath")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::ExportInfo> {
    static chromatic::js::ExportInfo unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::ExportInfo obj;

        obj.type = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "type"));

        obj.name = js_traits<std::string>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "name"));

        obj.address = js_traits<std::shared_ptr<chromatic::js::NativePointer>>::unwrap(ctx, JS_GetPropertyStr(ctx, v, "address"));

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::ExportInfo &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        JS_SetPropertyStr(ctx, obj, "type", js_traits<std::string>::wrap(ctx, val.type));

        JS_SetPropertyStr(ctx, obj, "name", js_traits<std::string>::wrap(ctx, val.name));

        JS_SetPropertyStr(ctx, obj, "address", js_traits<std::shared_ptr<chromatic::js::NativePointer>>::wrap(ctx, val.address));

        return obj;
    }
};
template<> struct js_bind<chromatic::js::ExportInfo> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::ExportInfo>("ExportInfo")
            .constructor<chromatic::js::ExportInfo>()
                .fun<&chromatic::js::ExportInfo::type>("type")
                .fun<&chromatic::js::ExportInfo::name>("name")
                .fun<&chromatic::js::ExportInfo::address>("address")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::NativeProcess> {
    static chromatic::js::NativeProcess unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativeProcess obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativeProcess &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativeProcess> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativeProcess>("NativeProcess")
            .constructor<>()
                    .static_property<&chromatic::js::NativeProcess::getArchitecture>("architecture")
                    .static_property<&chromatic::js::NativeProcess::getPlatform>("platform")
                    .static_property<&chromatic::js::NativeProcess::getPointerSize>("pointerSize")
                    .static_property<&chromatic::js::NativeProcess::getPageSize>("pageSize")
                    .static_property<&chromatic::js::NativeProcess::getProcessId>("processId")
                    .static_property<&chromatic::js::NativeProcess::getCurrentThreadId>("currentThreadId")
                .static_fun<&chromatic::js::NativeProcess::getArchitecture>("getArchitecture")
                .static_fun<&chromatic::js::NativeProcess::getPlatform>("getPlatform")
                .static_fun<&chromatic::js::NativeProcess::getPointerSize>("getPointerSize")
                .static_fun<&chromatic::js::NativeProcess::getPageSize>("getPageSize")
                .static_fun<&chromatic::js::NativeProcess::getProcessId>("getProcessId")
                .static_fun<&chromatic::js::NativeProcess::getCurrentThreadId>("getCurrentThreadId")
                .static_fun<&chromatic::js::NativeProcess::enumerateModules>("enumerateModules")
                .static_fun<&chromatic::js::NativeProcess::enumerateRanges>("enumerateRanges")
                .static_fun<&chromatic::js::NativeProcess::findExportByName>("findExportByName")
                .static_fun<&chromatic::js::NativeProcess::findModuleByAddress>("findModuleByAddress")
                .static_fun<&chromatic::js::NativeProcess::findModuleByName>("findModuleByName")
                .static_fun<&chromatic::js::NativeProcess::enumerateExports>("enumerateExports")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::ScriptLifecycle> {
    static chromatic::js::ScriptLifecycle unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::ScriptLifecycle obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::ScriptLifecycle &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::ScriptLifecycle> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::ScriptLifecycle>("ScriptLifecycle")
            .constructor<>()
                .static_fun<&chromatic::js::ScriptLifecycle::onDispose>("onDispose")
                .static_fun<&chromatic::js::ScriptLifecycle::removeDisposeCallback>("removeDisposeCallback")
                .static_fun<&chromatic::js::ScriptLifecycle::removeAllDisposeCallbacks>("removeAllDisposeCallbacks")
                .static_fun<&chromatic::js::ScriptLifecycle::_callDisposeCallbacks>("_callDisposeCallbacks")
            ;
    }
};

template <> struct qjs::js_traits<chromatic::js::NativeCModule> {
    static chromatic::js::NativeCModule unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::NativeCModule obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::NativeCModule &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::NativeCModule> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::NativeCModule>("NativeCModule")
            .constructor<std::string, std::vector<std::string>, std::vector<uint64_t>>()
                .fun<&chromatic::js::NativeCModule::getSymbol>("getSymbol")
                .fun<&chromatic::js::NativeCModule::listSymbols>("listSymbols")
                .fun<&chromatic::js::NativeCModule::dispose>("dispose")
            ;
    }
};

inline void chromatic_bindAll(qjs::Context::Module &mod) {

    js_bind<chromatic::js::NativePointer>::bind(mod);

    js_bind<chromatic::js::console>::bind(mod);

    js_bind<chromatic::js::NativeSoftwareBreakpoint>::bind(mod);

    js_bind<chromatic::js::InstructionInfo>::bind(mod);

    js_bind<chromatic::js::InstructionAnalysis>::bind(mod);

    js_bind<chromatic::js::XrefResult>::bind(mod);

    js_bind<chromatic::js::NativeDisassembler>::bind(mod);

    js_bind<chromatic::js::ExceptionContext>::bind(mod);

    js_bind<chromatic::js::NativeExceptionHandler>::bind(mod);

    js_bind<chromatic::js::NativeFFI>::bind(mod);

    js_bind<chromatic::js::NativeHardwareBreakpoint>::bind(mod);

    js_bind<chromatic::js::NativeInterceptor>::bind(mod);

    js_bind<chromatic::js::ScanMatch>::bind(mod);

    js_bind<chromatic::js::NativeMemory>::bind(mod);

    js_bind<chromatic::js::MemoryAccessDetails>::bind(mod);

    js_bind<chromatic::js::NativeMemoryAccessMonitor>::bind(mod);

    js_bind<chromatic::js::SegmentInfo>::bind(mod);

    js_bind<chromatic::js::ModuleInfo>::bind(mod);

    js_bind<chromatic::js::RangeInfo>::bind(mod);

    js_bind<chromatic::js::ExportInfo>::bind(mod);

    js_bind<chromatic::js::NativeProcess>::bind(mod);

    js_bind<chromatic::js::ScriptLifecycle>::bind(mod);

    js_bind<chromatic::js::NativeCModule>::bind(mod);

}
