// This file is generated by bindgen
// Do not modify this file manually!

declare module 'chromatic' {

export class console {
	/**
     * 
     * @param message: string
     * @returns void
     */
    log(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    error(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    warn(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    info(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    debug(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    trace(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    group(message: string): void
	groupEnd(): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    table(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    time(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    timeEnd(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    count(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    countReset(message: string): void
	/**
     * 
     * @param condition: boolean
     * @param message: string
     * @returns void
     */
    assert(condition: boolean, message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    dir(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    dirxml(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    profile(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    profileEnd(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    timeStamp(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    timeline(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    timelineEnd(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    timeLog(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    timeLine(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    timeLineEnd(message: string): void
}
}

