// This file is generated by bindgen
// Do not modify this file manually!

declare module 'chromatic' {

export class console {
	/**
     * 
     * @param message: string
     * @returns void
     */
    static log(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static error(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static warn(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static info(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static debug(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static trace(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static group(message: string): void
	static groupEnd(): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static table(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static time(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static timeEnd(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static count(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static countReset(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static dir(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static dirxml(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static profile(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static profileEnd(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static timeStamp(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static timeline(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static timelineEnd(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static timeLog(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static timeLine(message: string): void
	/**
     * 
     * @param message: string
     * @returns void
     */
    static timeLineEnd(message: string): void
}
export class NativeSoftwareBreakpoint {
	/**
     *  Set a software breakpoint at address (hex).
     *  Writes INT3 (x86) or BRK #1 (ARM64).
     *  onHit receives cpuContext pointer (hex) when triggered.
     *  Returns breakpointId (hex).
     * @param address: string
     * @param onHit: ((arg1: string) => void)
     * @returns string
     */
    static set(address: string, onHit: ((arg1: string) => void)): string
	/**
     *  Remove a breakpoint by ID. Restores original byte(s).
     * @param breakpointId: string
     * @returns void
     */
    static remove(breakpointId: string): void
	/**
     *  Remove all software breakpoints.
      @returns void
     */
    static removeAll(): void
}
export class InstructionInfo {
	mnemonic: string
	opStr: string
	size: number
	/**
     *  hex
     */
    bytes: string
	/**
     *  hex
     */
    address: string
	groups: Array<number>
	regsRead: Array<number>
	regsWrite: Array<number>
}
export class InstructionAnalysis {
	isBranch: boolean
	isCall: boolean
	isRelative: boolean
	/**
     *  hex
     */
    target: string
	isPcRelative: boolean
	size: number
}
export class XrefResult {
	/**
     *  hex — the referring instruction's address
     */
    address: string
	/**
     *  "call" | "branch" | "data"
     */
    type: string
	/**
     *  instruction size
     */
    size: number
}
export class NativeDisassembler {
	/**
     *  Disassemble one instruction at address.
     * @param address: string
     * @returns InstructionInfo
     */
    static disassembleOne(address: string): InstructionInfo
	/**
     *  Disassemble `count` instructions starting at address.
     * @param address: string
     * @param count: number
     * @returns Array<InstructionInfo>
     */
    static disassemble(address: string, count: number): Array<InstructionInfo>
	/**
     *  Analyze instruction for control flow.
     * @param address: string
     * @returns InstructionAnalysis
     */
    static analyzeInstruction(address: string): InstructionAnalysis
	/**
     *  Find all instructions in [rangeStart, rangeStart+rangeSize) that
     *  reference targetAddr (call, branch, or data/PC-relative load).
     * @param rangeStart: string
     * @param rangeSize: number
     * @param targetAddr: string
     * @returns Array<XrefResult>
     */
    static findXrefs(rangeStart: string, rangeSize: number, targetAddr: string): Array<XrefResult>
	/**
     *  Find xrefs within a named module.
     * @param moduleName: string
     * @param targetAddr: string
     * @returns Array<XrefResult>
     */
    static findXrefsInModule(moduleName: string, targetAddr: string): Array<XrefResult>
	/**
     *  Async variant of findXrefs.
     * @param rangeStart: string
     * @param rangeSize: number
     * @param targetAddr: string
     * @returns Promise<Array<XrefResult>>
     */
    static findXrefsAsync(rangeStart: string, rangeSize: number, targetAddr: string): Promise<Array<XrefResult>>
	/**
     *  Async variant of findXrefsInModule.
     * @param moduleName: string
     * @param targetAddr: string
     * @returns Promise<Array<XrefResult>>
     */
    static findXrefsInModuleAsync(moduleName: string, targetAddr: string): Promise<Array<XrefResult>>
	/**
     *  Iterate instructions starting at `address` for `count` instructions,
     *  calling `filter` on each. Return only instructions for which filter
     *  returns true.
     * @param address: string
     * @param count: number
     * @param filter: ((arg1: InstructionInfo) => boolean)
     * @returns Array<InstructionInfo>
     */
    static filterInstructions(address: string, count: number, filter: ((arg1: InstructionInfo) => boolean)): Array<InstructionInfo>
	/**
     *  Async variant of filterInstructions.
     * @param address: string
     * @param count: number
     * @param filter: ((arg1: InstructionInfo) => boolean)
     * @returns Promise<Array<InstructionInfo>>
     */
    static filterInstructionsAsync(address: string, count: number, filter: ((arg1: InstructionInfo) => boolean)): Promise<Array<InstructionInfo>>
}
export const enum ExceptionType {
	AccessViolation,
	BusError,
	Breakpoint,
	SingleStep,
	IllegalInstruction,
	Unknown,
}
export const enum AccessType {
	Read,
	Write,
	Execute,
	Unknown,
}
export const enum HandleAction {
	Handled,
	NotHandled,
}
export class ExceptionContext {
	type: ExceptionType
	/**
     *  Address that faulted (or PC for breakpoints)
     */
    faultAddress: number
	/**
     *  For SIGSEGV: read/write/execute
     */
    accessType: AccessType
	/**
     *  Get the program counter from the platform context.
     */
    get pc(): number;
    set pc(value: number);
}
export class NativeExceptionHandler {
	/**
     *  Enable the global exception handler (opt-in, idempotent).
      @returns void
     */
    static enable(): void
	/**
     *  Disable the global exception handler. Restores original handlers.
      @returns void
     */
    static disable(): void
	/**
     *  Returns true if currently enabled.
      @returns boolean
     */
    static isEnabled(): boolean
	/**
     *  Register a JS callback for a given exception type.
     *  type:
     *  "access_violation"|"breakpoint"|"single_step"|"bus_error"|"illegal_instruction"
     *  The callback receives (exceptionType: string, faultAddress: hex string).
     *  Returns callbackId (hex) for removal.
     * @param type: string
     * @param callback: ((arg1: string, arg2: string) => void)
     * @returns string
     */
    static addCallback(type: string, callback: ((arg1: string, arg2: string) => void)): string
	/**
     *  Remove a previously registered callback.
     * @param callbackId: string
     * @returns void
     */
    static removeCallback(callbackId: string): void
	/**
     *  Remove all registered callbacks.
      @returns void
     */
    static removeAllCallbacks(): void
}
export class NativeFFI {
	/**
     *  Call a native function at `address`.
     *  retType:
     *  "void","int","uint","long","ulong","int8","uint8",...,"float","double","pointer"
     *  argTypes: vector of type strings
     *  args: vector of argument values (numbers or hex strings for pointers)
     *  abi: "default","sysv","stdcall","win64"
     *  Returns: result as string (number or hex address)
     * @param address: string
     * @param retType: string
     * @param argTypes: Array<string>
     * @param args: Array<string>
     * @param abi: string
     * @returns string
     */
    static callFunction(address: string, retType: string, argTypes: Array<string>, args: Array<string>, abi: string): string
	/**
     *  Create a native callback closure.
     *  handler: JS function that receives args as vector of strings, returns
     *  result string Returns: address of the native closure as hex string
     * @param handler: ((arg1: Array<string>) => string)
     * @param retType: string
     * @param argTypes: Array<string>
     * @param abi: string
     * @returns string
     */
    static createCallback(handler: ((arg1: Array<string>) => string), retType: string, argTypes: Array<string>, abi: string): string
	/**
     *  Destroy a previously created callback closure
     * @param address: string
     * @returns void
     */
    static destroyCallback(address: string): void
}
export class NativeHardwareBreakpoint {
	/**
     *  Set a hardware breakpoint/watchpoint.
     *  address: hex target address
     *  type: "execute" | "write" | "readwrite"
     *  size: 1, 2, 4, or 8 bytes (for watchpoints; ignored for execute)
     *  onHit: callback receiving cpuContext pointer (hex)
     *  Returns breakpointId (hex).
     * @param address: string
     * @param type: string
     * @param size: number
     * @param onHit: ((arg1: string) => void)
     * @returns string
     */
    static set(address: string, type: string, size: number, onHit: ((arg1: string) => void)): string
	/**
     *  Remove a breakpoint by ID.
     * @param breakpointId: string
     * @returns void
     */
    static remove(breakpointId: string): void
	/**
     *  Remove all hardware breakpoints.
      @returns void
     */
    static removeAll(): void
	/**
     *  Max hardware breakpoints the platform supports.
      @returns number
     */
    static maxBreakpoints(): number
	/**
     *  Currently active count.
      @returns number
     */
    static activeCount(): number
}
export class NativeInterceptor {
	/**
     *  Attach an inline hook to `target`.
     *  onEnter/onLeave receive the cpuContext pointer as a hex string.
     *  Returns a hookId string used for detaching.
     * @param target: string
     * @param onEnter: ((arg1: string) => void)
     * @param onLeave: ((arg1: string) => void)
     * @returns string
     */
    static attach(target: string, onEnter: ((arg1: string) => void), onLeave: ((arg1: string) => void)): string
	/**
     *  Detach a hook by hookId.
     * @param hookId: string
     * @returns void
     */
    static detach(hookId: string): void
	/**
     *  Detach all active hooks.
      @returns void
     */
    static detachAll(): void
	/**
     *  Replace target function with replacement.
     *  Returns trampoline address (hex) to call the original function.
     * @param target: string
     * @param replacement: string
     * @returns string
     */
    static replace(target: string, replacement: string): string
	/**
     *  Revert a replacement.
     * @param target: string
     * @returns void
     */
    static revert(target: string): void
}
export class ScanMatch {
	/**
     *  hex
     */
    address: string
	size: number
}
export class NativeMemory {
	/**
     *  Read `size` bytes from `address` (hex string), return hex-encoded data
     * @param address: string
     * @param size: number
     * @returns string
     */
    static readMemory(address: string, size: number): string
	/**
     *  Like readMemory but returns empty string on access fault instead of
     *  crashing
     * @param address: string
     * @param size: number
     * @returns string
     */
    static safeReadMemory(address: string, size: number): string
	/**
     *  Write hex-encoded `hexData` to `address`
     * @param address: string
     * @param hexData: string
     * @returns void
     */
    static writeMemory(address: string, hexData: string): void
	/**
     *  Allocate `size` bytes of RWX memory, return address as hex string
     * @param size: number
     * @returns string
     */
    static allocateMemory(size: number): string
	/**
     *  Free previously allocated memory at `address` of given `size`
     * @param address: string
     * @param size: number
     * @returns void
     */
    static freeMemory(address: string, size: number): void
	/**
     *  Change memory protection. `protection` is like "rwx"/"r-x"/etc.
     *  Returns old protection string.
     * @param address: string
     * @param size: number
     * @param protection: string
     * @returns string
     */
    static protectMemory(address: string, size: number, protection: string): string
	/**
     *  Write bytes + flush instruction cache (for code patching)
     * @param address: string
     * @param hexBytes: string
     * @returns void
     */
    static patchCode(address: string, hexBytes: string): void
	/**
     *  Flush instruction cache for region
     * @param address: string
     * @param size: number
     * @returns void
     */
    static flushIcache(address: string, size: number): void
	/**
     *  Copy `size` bytes from `src` to `dst`
     * @param dst: string
     * @param src: string
     * @param size: number
     * @returns void
     */
    static copyMemory(dst: string, src: string, size: number): void
	/**
     *  Scan memory region for pattern (e.g. "48 8b ?? 00") using
     *  Boyer-Moore-Horspool with wildcard support.
     *  Returns vector of ScanMatch with address + pattern size.
     * @param address: string
     * @param size: number
     * @param pattern: string
     * @returns Array<ScanMatch>
     */
    static scanMemory(address: string, size: number, pattern: string): Array<ScanMatch>
	/**
     *  Scan within a named module for pattern.
     *  Internally looks up module base+size, then delegates to scanMemory.
     * @param moduleName: string
     * @param pattern: string
     * @returns Array<ScanMatch>
     */
    static scanModule(moduleName: string, pattern: string): Array<ScanMatch>
	/**
     *  Async variant of scanMemory — returns Lazy
     * <T
     * > (→ JS Promise).
     * @param address: string
     * @param size: number
     * @param pattern: string
     * @returns Promise<Array<ScanMatch>>
     */
    static scanMemoryAsync(address: string, size: number, pattern: string): Promise<Array<ScanMatch>>
	/**
     *  Async variant of scanModule — returns Lazy
     * <T
     * > (→ JS Promise).
     * @param moduleName: string
     * @param pattern: string
     * @returns Promise<Array<ScanMatch>>
     */
    static scanModuleAsync(moduleName: string, pattern: string): Promise<Array<ScanMatch>>
}
export class MemoryAccessDetails {
	/**
     *  hex — exact access address
     */
    address: string
	/**
     *  hex — page-aligned base
     */
    pageBase: string
	/**
     *  "read" | "write" | "execute"
     */
    operation: string
	/**
     *  which watched range triggered
     */
    rangeIndex: number
}
export class NativeMemoryAccessMonitor {
	/**
     *  Enable monitoring on memory ranges (one-shot per range).
     *  Removes permissions via mprotect, catches SIGSEGV on first access.
     *  When a watched range is accessed, permissions are permanently restored
     *  and the access is recorded.
     *  onAccess fires with (address, pageBase, operation, rangeIndex).
     *  Returns monitorId (hex).
     * @param addresses: Array<string>
     * @param sizes: Array<number>
     * @param onAccess: ((arg1: string, arg2: string, arg3: string, arg4: number) => void)
     * @returns string
     */
    static enable(addresses: Array<string>, sizes: Array<number>, onAccess: ((arg1: string, arg2: string, arg3: string, arg4: number) => void)): string
	/**
     *  Disable monitoring for a specific monitor.
     * @param monitorId: string
     * @returns void
     */
    static disable(monitorId: string): void
	/**
     *  Disable all active monitors.
      @returns void
     */
    static disableAll(): void
	/**
     *  Drain pending access events, calling the registered callbacks.
     *  Returns the number of events drained.
     *  This is called from JS context (safe for JS callbacks).
      @returns number
     */
    static drainPending(): number
}
export class SegmentInfo {
	base: number
	size: number
}
export class ModuleInfo {
	name: string
	/**
     *  hex address
     */
    base: string
	size: number
	path: string
	/**
     *  individual mapped regions (not exposed to JS)
     */
    segments: Array<SegmentInfo>
}
export class RangeInfo {
	/**
     *  hex address
     */
    base: string
	size: number
	protection: string
	/**
     *  empty if none
     */
    filePath: string
}
export class ExportInfo {
	type: string
	name: string
	/**
     *  hex address
     */
    address: string
}
export class NativeProcess {
	/**
     *  Returns "arm64" or "x64"
     */
    static get architecture(): string;
	/**
     *  Returns "windows", "linux", "darwin", or "android"
     */
    static get platform(): string;
	/**
     *  Returns pointer size in bytes (4 or 8)
     */
    static get pointerSize(): number;
	/**
     *  Returns system page size
     */
    static get pageSize(): number;
	/**
     *  Returns current process ID
     */
    static get processId(): number;
	/**
     *  Returns current thread ID as hex string
     */
    static get currentThreadId(): string;
	/**
     *  Returns vector of loaded modules
      @returns Array<ModuleInfo>
     */
    static enumerateModules(): Array<ModuleInfo>
	/**
     *  Returns vector of memory ranges matching protection
     * @param protection: string
     * @returns Array<RangeInfo>
     */
    static enumerateRanges(protection: string): Array<RangeInfo>
	/**
     *  Find export address by module and export name. Returns hex address or
     *  "0x0".
     * @param moduleName: string
     * @param exportName: string
     * @returns string
     */
    static findExportByName(moduleName: string, exportName: string): string
	/**
     *  Find module containing address, or nullptr
     * @param address: string
     * @returns ModuleInfo
     */
    static findModuleByAddress(address: string): ModuleInfo
	/**
     *  Find module by name, or nullptr
     * @param name: string
     * @returns ModuleInfo
     */
    static findModuleByName(name: string): ModuleInfo
	/**
     *  Enumerate exports of a module
     * @param moduleName: string
     * @returns Array<ExportInfo>
     */
    static enumerateExports(moduleName: string): Array<ExportInfo>
}
export class ScriptLifecycle {
	/**
     *  Register a callback to be called before script dispose/reload.
     *  Returns callbackId (hex) for removal.
     * @param callback: (() => void)
     * @returns string
     */
    static onDispose(callback: (() => void)): string
	/**
     *  Remove a dispose callback by ID.
     * @param callbackId: string
     * @returns void
     */
    static removeDisposeCallback(callbackId: string): void
	/**
     *  Remove all dispose callbacks.
      @returns void
     */
    static removeAllDisposeCallbacks(): void
	/**
     *  [Internal] Call all registered dispose callbacks, then clear them.
      @returns void
     */
    static _callDisposeCallbacks(): void
}
}

