// This file is generated by Breeze.JS Bindgen (https://github.com/breeze-shell/breeze-js-bindgen)
// Do not modify this file manually!

#pragma once
#include "binding_types.h"
#include "quickjspp.hpp"

template <typename T>
struct js_bind {
    static void bind(qjs::Context::Module &mod) {}
};

template <> struct qjs::js_traits<chromatic::js::console> {
    static chromatic::js::console unwrap(JSContext *ctx, JSValueConst v) {
        chromatic::js::console obj;

        return obj;
    }

    static JSValue wrap(JSContext *ctx, const chromatic::js::console &val) noexcept {
        JSValue obj = JS_NewObject(ctx);

        return obj;
    }
};
template<> struct js_bind<chromatic::js::console> {
    static void bind(qjs::Context::Module &mod) {
        mod.class_<chromatic::js::console>("console")
            .constructor<>()
                .fun<&chromatic::js::console::log>("log")
                .fun<&chromatic::js::console::error>("error")
                .fun<&chromatic::js::console::warn>("warn")
                .fun<&chromatic::js::console::info>("info")
                .fun<&chromatic::js::console::debug>("debug")
                .fun<&chromatic::js::console::trace>("trace")
                .fun<&chromatic::js::console::group>("group")
                .fun<&chromatic::js::console::groupEnd>("groupEnd")
                .fun<&chromatic::js::console::table>("table")
                .fun<&chromatic::js::console::time>("time")
                .fun<&chromatic::js::console::timeEnd>("timeEnd")
                .fun<&chromatic::js::console::count>("count")
                .fun<&chromatic::js::console::countReset>("countReset")
                .fun<&chromatic::js::console::dir>("dir")
                .fun<&chromatic::js::console::dirxml>("dirxml")
                .fun<&chromatic::js::console::profile>("profile")
                .fun<&chromatic::js::console::profileEnd>("profileEnd")
                .fun<&chromatic::js::console::timeStamp>("timeStamp")
                .fun<&chromatic::js::console::timeline>("timeline")
                .fun<&chromatic::js::console::timelineEnd>("timelineEnd")
                .fun<&chromatic::js::console::timeLog>("timeLog")
                .fun<&chromatic::js::console::timeLine>("timeLine")
                .fun<&chromatic::js::console::timeLineEnd>("timeLineEnd")
            ;
    }
};

inline void bindAll(qjs::Context::Module &mod) {

    js_bind<chromatic::js::console>::bind(mod);

}
